"""Add bypass rules table

Revision ID: 3ff74d710b99
Revises: b85812318571
Create Date: 2026-07-13 09:12:26.716347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff74d710b99'
down_revision: Union[str, None] = 'b85812318571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bypass_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bypass_rules_domain'), 'bypass_rules', ['domain'], unique=False)
    op.create_index(op.f('ix_bypass_rules_id'), 'bypass_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bypass_rules_id'), table_name='bypass_rules')
    op.drop_index(op.f('ix_bypass_rules_domain'), table_name='bypass_rules')
    op.drop_table('bypass_rules')
    # ### end Alembic commands ###
