"""initial_schema

Revision ID: a789a9fd035d
Revises:   # noqa: W291
Create Date: 2026-07-12 06:15:05.405134

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a789a9fd035d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promocodes",
        sa.Column("code", sa.String(), nullable=False),  # noqa: E128
        sa.Column("discount_pct", sa.Integer(), nullable=False),  # noqa: E122
        sa.Column("max_uses", sa.Integer(), nullable=False),  # noqa: E122
        sa.Column("current_uses", sa.Integer(), nullable=False),  # noqa: E122
        sa.Column(
            "expires_at", sa.DateTime(timezone=True), nullable=True
        ),  # noqa: E122, E501
        sa.PrimaryKeyConstraint("code"),  # noqa: E122
    )
    op.create_index(
        op.f("ix_promocodes_code"), "promocodes", ["code"], unique=False
    )  # noqa: E501
    op.create_table(
        "servers",
        sa.Column("id", sa.Integer(), nullable=False),  # noqa: E128
        sa.Column("country", sa.String(), nullable=False),  # noqa: E122
        sa.Column("domain", sa.String(), nullable=False),  # noqa: E122
        sa.Column("api_secret", sa.String(), nullable=False),  # noqa: E122
        sa.Column("is_active", sa.Boolean(), nullable=False),  # noqa: E122
        sa.PrimaryKeyConstraint("id"),  # noqa: E122
    )
    op.create_index(op.f("ix_servers_id"), "servers", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),  # noqa: E128
        sa.Column("tg_id", sa.BigInteger(), nullable=False),  # noqa: E122
        sa.Column("username", sa.String(), nullable=True),  # noqa: E122
        sa.Column("referrer_id", sa.Integer(), nullable=True),  # noqa: E122
        sa.Column("trial_used", sa.Boolean(), nullable=False),  # noqa: E122
        sa.Column("extra_keys", sa.Integer(), nullable=False),  # noqa: E122
        sa.Column("is_banned", sa.Boolean(), nullable=False),  # noqa: E122
        sa.Column(
            "ref_bonus_triggered", sa.Boolean(), nullable=False
        ),  # noqa: E122, E501
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E122, E501
        sa.ForeignKeyConstraint(
            ["referrer_id"],
            ["users.id"],
        ),  # noqa: E122
        sa.PrimaryKeyConstraint("id"),  # noqa: E122
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_tg_id"), "users", ["tg_id"], unique=True)
    op.create_table(
        "keys",
        sa.Column("id", sa.Integer(), nullable=False),  # noqa: E128
        sa.Column("user_id", sa.Integer(), nullable=False),  # noqa: E122
        sa.Column("server_id", sa.Integer(), nullable=False),  # noqa: E122
        sa.Column("protocol", sa.String(), nullable=False),  # noqa: E122
        sa.Column("internal_ip", sa.String(), nullable=True),  # noqa: E122
        sa.Column("client_uuid", sa.String(), nullable=True),  # noqa: E122
        sa.Column("config_data", sa.String(), nullable=False),  # noqa: E122
        sa.Column("status", sa.String(), nullable=False),  # noqa: E122
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),  # noqa: E122
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),  # noqa: E122
        sa.PrimaryKeyConstraint("id"),  # noqa: E122
    )
    op.create_index(op.f("ix_keys_id"), "keys", ["id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),  # noqa: E128
        sa.Column("user_id", sa.Integer(), nullable=False),  # noqa: E122
        sa.Column("gateway_payment_id", sa.String(), nullable=True),  # noqa: E122
        sa.Column("amount", sa.BigInteger(), nullable=False),  # noqa: E122
        sa.Column("currency", sa.String(), nullable=False),  # noqa: E122
        sa.Column("status", sa.String(), nullable=False),  # noqa: E122
        sa.Column("payment_type", sa.String(), nullable=False),  # noqa: E122
        sa.Column("promocode", sa.String(), nullable=True),  # noqa: E122
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),  # noqa: E122, E501
        sa.ForeignKeyConstraint(
            ["promocode"],
            ["promocodes.code"],
        ),  # noqa: E122, E501
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),  # noqa: E122
        sa.PrimaryKeyConstraint("id"),  # noqa: E122
    )
    op.create_index(op.f("ix_payments_id"), "payments", ["id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),  # noqa: E128
        sa.Column("user_id", sa.Integer(), nullable=False),  # noqa: E122
        sa.Column("plan", sa.String(), nullable=False),  # noqa: E122
        sa.Column(
            "expires_at", sa.DateTime(timezone=True), nullable=False
        ),  # noqa: E122, E501
        sa.Column("base_device_limit", sa.Integer(), nullable=False),  # noqa: E122
        sa.Column("is_active", sa.Boolean(), nullable=False),  # noqa: E122
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),  # noqa: E122
        sa.PrimaryKeyConstraint("id"),  # noqa: E122
    )
    op.create_index(
        op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=False
    )  # noqa: E501
    op.create_table(
        "refund_tickets",
        sa.Column("id", sa.Integer(), nullable=False),  # noqa: E128
        sa.Column("user_id", sa.Integer(), nullable=False),  # noqa: E122
        sa.Column("payment_id", sa.Integer(), nullable=False),  # noqa: E122
        sa.Column(
            "amount_calculated", sa.BigInteger(), nullable=False
        ),  # noqa: E122, E501
        sa.Column("status", sa.String(), nullable=False),  # noqa: E122
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),  # noqa: E122
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),  # noqa: E122
        sa.PrimaryKeyConstraint("id"),  # noqa: E122
    )
    op.create_index(
        op.f("ix_refund_tickets_id"), "refund_tickets", ["id"], unique=False
    )  # noqa: E501
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refund_tickets_id"), table_name="refund_tickets")
    op.drop_table("refund_tickets")
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_payments_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_keys_id"), table_name="keys")
    op.drop_table("keys")
    op.drop_index(op.f("ix_users_tg_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_servers_id"), table_name="servers")
    op.drop_table("servers")
    op.drop_index(op.f("ix_promocodes_code"), table_name="promocodes")
    op.drop_table("promocodes")
    # ### end Alembic commands ###
