"""Add email auth to user

Revision ID: cfe08c333df5
Revises: b789a9fd035d
Create Date: 2026-07-12 08:27:46.718932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe08c333df5'
down_revision: Union[str, None] = 'b789a9fd035d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('notification_preference', sa.String(length=20), nullable=False))
    op.alter_column('users', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'tg_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('users', 'notification_preference')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
